/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.25.3
 * source: brevis/gateway.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./types";
import * as dependency_2 from "./../common/circuit_data";
import * as dependency_3 from "./../google/api/annotations";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export enum ErrCode {
    ERROR_CODE_UNDEFINED = 0,
    ERROR_CODE_SLOT_VALUE_PROOF_GENERATION_FAILED = 1,
    ERROR_CODE_TRANSACTION_PROOF_GENERATION_FAILED = 2
}
export enum CheckStatus {
    IN_PROGRESS = 0,
    COMPLETE = 1
}
export enum QueryOption {
    ZK_MODE = 0,
    OP_MODE = 1
}
export enum QueryStatus {
    QS_UNKNOWN = 0,
    QS_TO_BE_PAID = 1,
    QS_PAID = 2,
    QS_PROOF_READY = 3,
    QS_COMPLETE = 4,
    QS_FAILED = 5,
    QS_OP_MESSAGE_PENDING = 6,
    QS_OP_MESSAGE_READY = 7,
    QS_OP_SUBMITTED = 8,
    QS_OP_MESSAGE_SUBMISSION_FAILED = 9,
    QS_OP_DISPUTING = 10,
    QS_OP_ASK_FOR_QUERY_DATA = 11,
    QS_OP_QUERY_DATA_SUBMITTED = 12,
    QS_OP_QUERY_DATA_POST_FAILED = 13,
    QS_OP_ASK_FOR_QUERY_PROOF = 14,
    QS_OP_DISPUTED = 15,
    QS_OP_ATTESTED = 16,
    QS_REFUNDED = 17
}
export class ErrMsg extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        code?: ErrCode;
        msg?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("code" in data && data.code != undefined) {
                this.code = data.code;
            }
            if ("msg" in data && data.msg != undefined) {
                this.msg = data.msg;
            }
        }
    }
    get code() {
        return pb_1.Message.getFieldWithDefault(this, 1, ErrCode.ERROR_CODE_UNDEFINED) as ErrCode;
    }
    set code(value: ErrCode) {
        pb_1.Message.setField(this, 1, value);
    }
    get msg() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set msg(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        code?: ErrCode;
        msg?: string;
    }): ErrMsg {
        const message = new ErrMsg({});
        if (data.code != null) {
            message.code = data.code;
        }
        if (data.msg != null) {
            message.msg = data.msg;
        }
        return message;
    }
    toObject() {
        const data: {
            code?: ErrCode;
            msg?: string;
        } = {};
        if (this.code != null) {
            data.code = this.code;
        }
        if (this.msg != null) {
            data.msg = this.msg;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.code != ErrCode.ERROR_CODE_UNDEFINED)
            writer.writeEnum(1, this.code);
        if (this.msg.length)
            writer.writeString(2, this.msg);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ErrMsg {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ErrMsg();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.code = reader.readEnum();
                    break;
                case 2:
                    message.msg = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ErrMsg {
        return ErrMsg.deserialize(bytes);
    }
}
export class PrepareQueryRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        chain_id?: number;
        receipt_infos?: dependency_1.ReceiptInfo[];
        storage_query_infos?: dependency_1.StorageQueryInfo[];
        transaction_infos?: dependency_1.TransactionInfo[];
        app_circuit_info?: dependency_2.AppCircuitInfo;
        target_chain_id?: number;
        option?: QueryOption;
        /** @deprecated*/
        use_plonky2?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2, 3, 4], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("chain_id" in data && data.chain_id != undefined) {
                this.chain_id = data.chain_id;
            }
            if ("receipt_infos" in data && data.receipt_infos != undefined) {
                this.receipt_infos = data.receipt_infos;
            }
            if ("storage_query_infos" in data && data.storage_query_infos != undefined) {
                this.storage_query_infos = data.storage_query_infos;
            }
            if ("transaction_infos" in data && data.transaction_infos != undefined) {
                this.transaction_infos = data.transaction_infos;
            }
            if ("app_circuit_info" in data && data.app_circuit_info != undefined) {
                this.app_circuit_info = data.app_circuit_info;
            }
            if ("target_chain_id" in data && data.target_chain_id != undefined) {
                this.target_chain_id = data.target_chain_id;
            }
            if ("option" in data && data.option != undefined) {
                this.option = data.option;
            }
            if ("use_plonky2" in data && data.use_plonky2 != undefined) {
                this.use_plonky2 = data.use_plonky2;
            }
        }
    }
    get chain_id() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set chain_id(value: number) {
        pb_1.Message.setField(this, 1, value);
    }
    get receipt_infos() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.ReceiptInfo, 2) as dependency_1.ReceiptInfo[];
    }
    set receipt_infos(value: dependency_1.ReceiptInfo[]) {
        pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    get storage_query_infos() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.StorageQueryInfo, 3) as dependency_1.StorageQueryInfo[];
    }
    set storage_query_infos(value: dependency_1.StorageQueryInfo[]) {
        pb_1.Message.setRepeatedWrapperField(this, 3, value);
    }
    get transaction_infos() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.TransactionInfo, 4) as dependency_1.TransactionInfo[];
    }
    set transaction_infos(value: dependency_1.TransactionInfo[]) {
        pb_1.Message.setRepeatedWrapperField(this, 4, value);
    }
    get app_circuit_info() {
        return pb_1.Message.getWrapperField(this, dependency_2.AppCircuitInfo, 5) as dependency_2.AppCircuitInfo;
    }
    set app_circuit_info(value: dependency_2.AppCircuitInfo) {
        pb_1.Message.setWrapperField(this, 5, value);
    }
    get has_app_circuit_info() {
        return pb_1.Message.getField(this, 5) != null;
    }
    get target_chain_id() {
        return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
    }
    set target_chain_id(value: number) {
        pb_1.Message.setField(this, 6, value);
    }
    get option() {
        return pb_1.Message.getFieldWithDefault(this, 7, QueryOption.ZK_MODE) as QueryOption;
    }
    set option(value: QueryOption) {
        pb_1.Message.setField(this, 7, value);
    }
    /** @deprecated*/
    get use_plonky2() {
        return pb_1.Message.getFieldWithDefault(this, 8, false) as boolean;
    }
    /** @deprecated*/
    set use_plonky2(value: boolean) {
        pb_1.Message.setField(this, 8, value);
    }
    static fromObject(data: {
        chain_id?: number;
        receipt_infos?: ReturnType<typeof dependency_1.ReceiptInfo.prototype.toObject>[];
        storage_query_infos?: ReturnType<typeof dependency_1.StorageQueryInfo.prototype.toObject>[];
        transaction_infos?: ReturnType<typeof dependency_1.TransactionInfo.prototype.toObject>[];
        app_circuit_info?: ReturnType<typeof dependency_2.AppCircuitInfo.prototype.toObject>;
        target_chain_id?: number;
        option?: QueryOption;
        use_plonky2?: boolean;
    }): PrepareQueryRequest {
        const message = new PrepareQueryRequest({});
        if (data.chain_id != null) {
            message.chain_id = data.chain_id;
        }
        if (data.receipt_infos != null) {
            message.receipt_infos = data.receipt_infos.map(item => dependency_1.ReceiptInfo.fromObject(item));
        }
        if (data.storage_query_infos != null) {
            message.storage_query_infos = data.storage_query_infos.map(item => dependency_1.StorageQueryInfo.fromObject(item));
        }
        if (data.transaction_infos != null) {
            message.transaction_infos = data.transaction_infos.map(item => dependency_1.TransactionInfo.fromObject(item));
        }
        if (data.app_circuit_info != null) {
            message.app_circuit_info = dependency_2.AppCircuitInfo.fromObject(data.app_circuit_info);
        }
        if (data.target_chain_id != null) {
            message.target_chain_id = data.target_chain_id;
        }
        if (data.option != null) {
            message.option = data.option;
        }
        if (data.use_plonky2 != null) {
            message.use_plonky2 = data.use_plonky2;
        }
        return message;
    }
    toObject() {
        const data: {
            chain_id?: number;
            receipt_infos?: ReturnType<typeof dependency_1.ReceiptInfo.prototype.toObject>[];
            storage_query_infos?: ReturnType<typeof dependency_1.StorageQueryInfo.prototype.toObject>[];
            transaction_infos?: ReturnType<typeof dependency_1.TransactionInfo.prototype.toObject>[];
            app_circuit_info?: ReturnType<typeof dependency_2.AppCircuitInfo.prototype.toObject>;
            target_chain_id?: number;
            option?: QueryOption;
            use_plonky2?: boolean;
        } = {};
        if (this.chain_id != null) {
            data.chain_id = this.chain_id;
        }
        if (this.receipt_infos != null) {
            data.receipt_infos = this.receipt_infos.map((item: dependency_1.ReceiptInfo) => item.toObject());
        }
        if (this.storage_query_infos != null) {
            data.storage_query_infos = this.storage_query_infos.map((item: dependency_1.StorageQueryInfo) => item.toObject());
        }
        if (this.transaction_infos != null) {
            data.transaction_infos = this.transaction_infos.map((item: dependency_1.TransactionInfo) => item.toObject());
        }
        if (this.app_circuit_info != null) {
            data.app_circuit_info = this.app_circuit_info.toObject();
        }
        if (this.target_chain_id != null) {
            data.target_chain_id = this.target_chain_id;
        }
        if (this.option != null) {
            data.option = this.option;
        }
        if (this.use_plonky2 != null) {
            data.use_plonky2 = this.use_plonky2;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.chain_id != 0)
            writer.writeUint64(1, this.chain_id);
        if (this.receipt_infos.length)
            writer.writeRepeatedMessage(2, this.receipt_infos, (item: dependency_1.ReceiptInfo) => item.serialize(writer));
        if (this.storage_query_infos.length)
            writer.writeRepeatedMessage(3, this.storage_query_infos, (item: dependency_1.StorageQueryInfo) => item.serialize(writer));
        if (this.transaction_infos.length)
            writer.writeRepeatedMessage(4, this.transaction_infos, (item: dependency_1.TransactionInfo) => item.serialize(writer));
        if (this.has_app_circuit_info)
            writer.writeMessage(5, this.app_circuit_info, () => this.app_circuit_info.serialize(writer));
        if (this.target_chain_id != 0)
            writer.writeUint64(6, this.target_chain_id);
        if (this.option != QueryOption.ZK_MODE)
            writer.writeEnum(7, this.option);
        if (this.use_plonky2 != false)
            writer.writeBool(8, this.use_plonky2);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PrepareQueryRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PrepareQueryRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.chain_id = reader.readUint64();
                    break;
                case 2:
                    reader.readMessage(message.receipt_infos, () => pb_1.Message.addToRepeatedWrapperField(message, 2, dependency_1.ReceiptInfo.deserialize(reader), dependency_1.ReceiptInfo));
                    break;
                case 3:
                    reader.readMessage(message.storage_query_infos, () => pb_1.Message.addToRepeatedWrapperField(message, 3, dependency_1.StorageQueryInfo.deserialize(reader), dependency_1.StorageQueryInfo));
                    break;
                case 4:
                    reader.readMessage(message.transaction_infos, () => pb_1.Message.addToRepeatedWrapperField(message, 4, dependency_1.TransactionInfo.deserialize(reader), dependency_1.TransactionInfo));
                    break;
                case 5:
                    reader.readMessage(message.app_circuit_info, () => message.app_circuit_info = dependency_2.AppCircuitInfo.deserialize(reader));
                    break;
                case 6:
                    message.target_chain_id = reader.readUint64();
                    break;
                case 7:
                    message.option = reader.readEnum();
                    break;
                case 8:
                    message.use_plonky2 = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PrepareQueryRequest {
        return PrepareQueryRequest.deserialize(bytes);
    }
}
export class PrepareQueryResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        err?: ErrMsg;
        query_key?: QueryKey;
        fee?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("err" in data && data.err != undefined) {
                this.err = data.err;
            }
            if ("query_key" in data && data.query_key != undefined) {
                this.query_key = data.query_key;
            }
            if ("fee" in data && data.fee != undefined) {
                this.fee = data.fee;
            }
        }
    }
    get err() {
        return pb_1.Message.getWrapperField(this, ErrMsg, 1) as ErrMsg;
    }
    set err(value: ErrMsg) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get has_err() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get query_key() {
        return pb_1.Message.getWrapperField(this, QueryKey, 2) as QueryKey;
    }
    set query_key(value: QueryKey) {
        pb_1.Message.setWrapperField(this, 2, value);
    }
    get has_query_key() {
        return pb_1.Message.getField(this, 2) != null;
    }
    get fee() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set fee(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    static fromObject(data: {
        err?: ReturnType<typeof ErrMsg.prototype.toObject>;
        query_key?: ReturnType<typeof QueryKey.prototype.toObject>;
        fee?: string;
    }): PrepareQueryResponse {
        const message = new PrepareQueryResponse({});
        if (data.err != null) {
            message.err = ErrMsg.fromObject(data.err);
        }
        if (data.query_key != null) {
            message.query_key = QueryKey.fromObject(data.query_key);
        }
        if (data.fee != null) {
            message.fee = data.fee;
        }
        return message;
    }
    toObject() {
        const data: {
            err?: ReturnType<typeof ErrMsg.prototype.toObject>;
            query_key?: ReturnType<typeof QueryKey.prototype.toObject>;
            fee?: string;
        } = {};
        if (this.err != null) {
            data.err = this.err.toObject();
        }
        if (this.query_key != null) {
            data.query_key = this.query_key.toObject();
        }
        if (this.fee != null) {
            data.fee = this.fee;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_err)
            writer.writeMessage(1, this.err, () => this.err.serialize(writer));
        if (this.has_query_key)
            writer.writeMessage(2, this.query_key, () => this.query_key.serialize(writer));
        if (this.fee.length)
            writer.writeString(3, this.fee);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PrepareQueryResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PrepareQueryResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.err, () => message.err = ErrMsg.deserialize(reader));
                    break;
                case 2:
                    reader.readMessage(message.query_key, () => message.query_key = QueryKey.deserialize(reader));
                    break;
                case 3:
                    message.fee = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PrepareQueryResponse {
        return PrepareQueryResponse.deserialize(bytes);
    }
}
export class SubmitAppCircuitProofRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        query_key?: QueryKey;
        target_chain_id?: number;
        proof?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("query_key" in data && data.query_key != undefined) {
                this.query_key = data.query_key;
            }
            if ("target_chain_id" in data && data.target_chain_id != undefined) {
                this.target_chain_id = data.target_chain_id;
            }
            if ("proof" in data && data.proof != undefined) {
                this.proof = data.proof;
            }
        }
    }
    get query_key() {
        return pb_1.Message.getWrapperField(this, QueryKey, 1) as QueryKey;
    }
    set query_key(value: QueryKey) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get has_query_key() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get target_chain_id() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set target_chain_id(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    get proof() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set proof(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    static fromObject(data: {
        query_key?: ReturnType<typeof QueryKey.prototype.toObject>;
        target_chain_id?: number;
        proof?: string;
    }): SubmitAppCircuitProofRequest {
        const message = new SubmitAppCircuitProofRequest({});
        if (data.query_key != null) {
            message.query_key = QueryKey.fromObject(data.query_key);
        }
        if (data.target_chain_id != null) {
            message.target_chain_id = data.target_chain_id;
        }
        if (data.proof != null) {
            message.proof = data.proof;
        }
        return message;
    }
    toObject() {
        const data: {
            query_key?: ReturnType<typeof QueryKey.prototype.toObject>;
            target_chain_id?: number;
            proof?: string;
        } = {};
        if (this.query_key != null) {
            data.query_key = this.query_key.toObject();
        }
        if (this.target_chain_id != null) {
            data.target_chain_id = this.target_chain_id;
        }
        if (this.proof != null) {
            data.proof = this.proof;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_query_key)
            writer.writeMessage(1, this.query_key, () => this.query_key.serialize(writer));
        if (this.target_chain_id != 0)
            writer.writeUint64(2, this.target_chain_id);
        if (this.proof.length)
            writer.writeString(3, this.proof);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SubmitAppCircuitProofRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SubmitAppCircuitProofRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.query_key, () => message.query_key = QueryKey.deserialize(reader));
                    break;
                case 2:
                    message.target_chain_id = reader.readUint64();
                    break;
                case 3:
                    message.proof = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SubmitAppCircuitProofRequest {
        return SubmitAppCircuitProofRequest.deserialize(bytes);
    }
}
export class SubmitAppCircuitProofResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        err?: ErrMsg;
        success?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("err" in data && data.err != undefined) {
                this.err = data.err;
            }
            if ("success" in data && data.success != undefined) {
                this.success = data.success;
            }
        }
    }
    get err() {
        return pb_1.Message.getWrapperField(this, ErrMsg, 1) as ErrMsg;
    }
    set err(value: ErrMsg) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get has_err() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get success() {
        return pb_1.Message.getFieldWithDefault(this, 2, false) as boolean;
    }
    set success(value: boolean) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        err?: ReturnType<typeof ErrMsg.prototype.toObject>;
        success?: boolean;
    }): SubmitAppCircuitProofResponse {
        const message = new SubmitAppCircuitProofResponse({});
        if (data.err != null) {
            message.err = ErrMsg.fromObject(data.err);
        }
        if (data.success != null) {
            message.success = data.success;
        }
        return message;
    }
    toObject() {
        const data: {
            err?: ReturnType<typeof ErrMsg.prototype.toObject>;
            success?: boolean;
        } = {};
        if (this.err != null) {
            data.err = this.err.toObject();
        }
        if (this.success != null) {
            data.success = this.success;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_err)
            writer.writeMessage(1, this.err, () => this.err.serialize(writer));
        if (this.success != false)
            writer.writeBool(2, this.success);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SubmitAppCircuitProofResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SubmitAppCircuitProofResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.err, () => message.err = ErrMsg.deserialize(reader));
                    break;
                case 2:
                    message.success = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SubmitAppCircuitProofResponse {
        return SubmitAppCircuitProofResponse.deserialize(bytes);
    }
}
export class GetQueryStatusRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        query_key?: QueryKey;
        target_chain_id?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("query_key" in data && data.query_key != undefined) {
                this.query_key = data.query_key;
            }
            if ("target_chain_id" in data && data.target_chain_id != undefined) {
                this.target_chain_id = data.target_chain_id;
            }
        }
    }
    get query_key() {
        return pb_1.Message.getWrapperField(this, QueryKey, 1) as QueryKey;
    }
    set query_key(value: QueryKey) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get has_query_key() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get target_chain_id() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set target_chain_id(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        query_key?: ReturnType<typeof QueryKey.prototype.toObject>;
        target_chain_id?: number;
    }): GetQueryStatusRequest {
        const message = new GetQueryStatusRequest({});
        if (data.query_key != null) {
            message.query_key = QueryKey.fromObject(data.query_key);
        }
        if (data.target_chain_id != null) {
            message.target_chain_id = data.target_chain_id;
        }
        return message;
    }
    toObject() {
        const data: {
            query_key?: ReturnType<typeof QueryKey.prototype.toObject>;
            target_chain_id?: number;
        } = {};
        if (this.query_key != null) {
            data.query_key = this.query_key.toObject();
        }
        if (this.target_chain_id != null) {
            data.target_chain_id = this.target_chain_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_query_key)
            writer.writeMessage(1, this.query_key, () => this.query_key.serialize(writer));
        if (this.target_chain_id != 0)
            writer.writeUint64(2, this.target_chain_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetQueryStatusRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetQueryStatusRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.query_key, () => message.query_key = QueryKey.deserialize(reader));
                    break;
                case 2:
                    message.target_chain_id = reader.readUint64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GetQueryStatusRequest {
        return GetQueryStatusRequest.deserialize(bytes);
    }
}
export class GetQueryStatusResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        err?: ErrMsg;
        status?: QueryStatus;
        tx_hash?: string;
        proof?: string;
        proof_data?: ProofData;
        circuit_output?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("err" in data && data.err != undefined) {
                this.err = data.err;
            }
            if ("status" in data && data.status != undefined) {
                this.status = data.status;
            }
            if ("tx_hash" in data && data.tx_hash != undefined) {
                this.tx_hash = data.tx_hash;
            }
            if ("proof" in data && data.proof != undefined) {
                this.proof = data.proof;
            }
            if ("proof_data" in data && data.proof_data != undefined) {
                this.proof_data = data.proof_data;
            }
            if ("circuit_output" in data && data.circuit_output != undefined) {
                this.circuit_output = data.circuit_output;
            }
        }
    }
    get err() {
        return pb_1.Message.getWrapperField(this, ErrMsg, 1) as ErrMsg;
    }
    set err(value: ErrMsg) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get has_err() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get status() {
        return pb_1.Message.getFieldWithDefault(this, 2, QueryStatus.QS_UNKNOWN) as QueryStatus;
    }
    set status(value: QueryStatus) {
        pb_1.Message.setField(this, 2, value);
    }
    get tx_hash() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set tx_hash(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get proof() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set proof(value: string) {
        pb_1.Message.setField(this, 4, value);
    }
    get proof_data() {
        return pb_1.Message.getWrapperField(this, ProofData, 5) as ProofData;
    }
    set proof_data(value: ProofData) {
        pb_1.Message.setWrapperField(this, 5, value);
    }
    get has_proof_data() {
        return pb_1.Message.getField(this, 5) != null;
    }
    get circuit_output() {
        return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
    }
    set circuit_output(value: string) {
        pb_1.Message.setField(this, 6, value);
    }
    static fromObject(data: {
        err?: ReturnType<typeof ErrMsg.prototype.toObject>;
        status?: QueryStatus;
        tx_hash?: string;
        proof?: string;
        proof_data?: ReturnType<typeof ProofData.prototype.toObject>;
        circuit_output?: string;
    }): GetQueryStatusResponse {
        const message = new GetQueryStatusResponse({});
        if (data.err != null) {
            message.err = ErrMsg.fromObject(data.err);
        }
        if (data.status != null) {
            message.status = data.status;
        }
        if (data.tx_hash != null) {
            message.tx_hash = data.tx_hash;
        }
        if (data.proof != null) {
            message.proof = data.proof;
        }
        if (data.proof_data != null) {
            message.proof_data = ProofData.fromObject(data.proof_data);
        }
        if (data.circuit_output != null) {
            message.circuit_output = data.circuit_output;
        }
        return message;
    }
    toObject() {
        const data: {
            err?: ReturnType<typeof ErrMsg.prototype.toObject>;
            status?: QueryStatus;
            tx_hash?: string;
            proof?: string;
            proof_data?: ReturnType<typeof ProofData.prototype.toObject>;
            circuit_output?: string;
        } = {};
        if (this.err != null) {
            data.err = this.err.toObject();
        }
        if (this.status != null) {
            data.status = this.status;
        }
        if (this.tx_hash != null) {
            data.tx_hash = this.tx_hash;
        }
        if (this.proof != null) {
            data.proof = this.proof;
        }
        if (this.proof_data != null) {
            data.proof_data = this.proof_data.toObject();
        }
        if (this.circuit_output != null) {
            data.circuit_output = this.circuit_output;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_err)
            writer.writeMessage(1, this.err, () => this.err.serialize(writer));
        if (this.status != QueryStatus.QS_UNKNOWN)
            writer.writeEnum(2, this.status);
        if (this.tx_hash.length)
            writer.writeString(3, this.tx_hash);
        if (this.proof.length)
            writer.writeString(4, this.proof);
        if (this.has_proof_data)
            writer.writeMessage(5, this.proof_data, () => this.proof_data.serialize(writer));
        if (this.circuit_output.length)
            writer.writeString(6, this.circuit_output);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetQueryStatusResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetQueryStatusResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.err, () => message.err = ErrMsg.deserialize(reader));
                    break;
                case 2:
                    message.status = reader.readEnum();
                    break;
                case 3:
                    message.tx_hash = reader.readString();
                    break;
                case 4:
                    message.proof = reader.readString();
                    break;
                case 5:
                    reader.readMessage(message.proof_data, () => message.proof_data = ProofData.deserialize(reader));
                    break;
                case 6:
                    message.circuit_output = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GetQueryStatusResponse {
        return GetQueryStatusResponse.deserialize(bytes);
    }
}
export class GetQueryInfoForOPRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        query_hash?: string;
        target_chain_id?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("query_hash" in data && data.query_hash != undefined) {
                this.query_hash = data.query_hash;
            }
            if ("target_chain_id" in data && data.target_chain_id != undefined) {
                this.target_chain_id = data.target_chain_id;
            }
        }
    }
    get query_hash() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set query_hash(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get target_chain_id() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set target_chain_id(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        query_hash?: string;
        target_chain_id?: number;
    }): GetQueryInfoForOPRequest {
        const message = new GetQueryInfoForOPRequest({});
        if (data.query_hash != null) {
            message.query_hash = data.query_hash;
        }
        if (data.target_chain_id != null) {
            message.target_chain_id = data.target_chain_id;
        }
        return message;
    }
    toObject() {
        const data: {
            query_hash?: string;
            target_chain_id?: number;
        } = {};
        if (this.query_hash != null) {
            data.query_hash = this.query_hash;
        }
        if (this.target_chain_id != null) {
            data.target_chain_id = this.target_chain_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.query_hash.length)
            writer.writeString(1, this.query_hash);
        if (this.target_chain_id != 0)
            writer.writeUint64(2, this.target_chain_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetQueryInfoForOPRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetQueryInfoForOPRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.query_hash = reader.readString();
                    break;
                case 2:
                    message.target_chain_id = reader.readUint64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GetQueryInfoForOPRequest {
        return GetQueryInfoForOPRequest.deserialize(bytes);
    }
}
export class GetQueryInfoForOPResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        err?: ErrMsg;
        query_info?: Uint8Array;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("err" in data && data.err != undefined) {
                this.err = data.err;
            }
            if ("query_info" in data && data.query_info != undefined) {
                this.query_info = data.query_info;
            }
        }
    }
    get err() {
        return pb_1.Message.getWrapperField(this, ErrMsg, 1) as ErrMsg;
    }
    set err(value: ErrMsg) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get has_err() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get query_info() {
        return pb_1.Message.getFieldWithDefault(this, 2, new Uint8Array(0)) as Uint8Array;
    }
    set query_info(value: Uint8Array) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        err?: ReturnType<typeof ErrMsg.prototype.toObject>;
        query_info?: Uint8Array;
    }): GetQueryInfoForOPResponse {
        const message = new GetQueryInfoForOPResponse({});
        if (data.err != null) {
            message.err = ErrMsg.fromObject(data.err);
        }
        if (data.query_info != null) {
            message.query_info = data.query_info;
        }
        return message;
    }
    toObject() {
        const data: {
            err?: ReturnType<typeof ErrMsg.prototype.toObject>;
            query_info?: Uint8Array;
        } = {};
        if (this.err != null) {
            data.err = this.err.toObject();
        }
        if (this.query_info != null) {
            data.query_info = this.query_info;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_err)
            writer.writeMessage(1, this.err, () => this.err.serialize(writer));
        if (this.query_info.length)
            writer.writeBytes(2, this.query_info);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetQueryInfoForOPResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetQueryInfoForOPResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.err, () => message.err = ErrMsg.deserialize(reader));
                    break;
                case 2:
                    message.query_info = reader.readBytes();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GetQueryInfoForOPResponse {
        return GetQueryInfoForOPResponse.deserialize(bytes);
    }
}
export class GetSingleRunParamsRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        query_key?: QueryKey;
        target_chain_id?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("query_key" in data && data.query_key != undefined) {
                this.query_key = data.query_key;
            }
            if ("target_chain_id" in data && data.target_chain_id != undefined) {
                this.target_chain_id = data.target_chain_id;
            }
        }
    }
    get query_key() {
        return pb_1.Message.getWrapperField(this, QueryKey, 1) as QueryKey;
    }
    set query_key(value: QueryKey) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get has_query_key() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get target_chain_id() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set target_chain_id(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        query_key?: ReturnType<typeof QueryKey.prototype.toObject>;
        target_chain_id?: number;
    }): GetSingleRunParamsRequest {
        const message = new GetSingleRunParamsRequest({});
        if (data.query_key != null) {
            message.query_key = QueryKey.fromObject(data.query_key);
        }
        if (data.target_chain_id != null) {
            message.target_chain_id = data.target_chain_id;
        }
        return message;
    }
    toObject() {
        const data: {
            query_key?: ReturnType<typeof QueryKey.prototype.toObject>;
            target_chain_id?: number;
        } = {};
        if (this.query_key != null) {
            data.query_key = this.query_key.toObject();
        }
        if (this.target_chain_id != null) {
            data.target_chain_id = this.target_chain_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_query_key)
            writer.writeMessage(1, this.query_key, () => this.query_key.serialize(writer));
        if (this.target_chain_id != 0)
            writer.writeUint64(2, this.target_chain_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetSingleRunParamsRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetSingleRunParamsRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.query_key, () => message.query_key = QueryKey.deserialize(reader));
                    break;
                case 2:
                    message.target_chain_id = reader.readUint64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GetSingleRunParamsRequest {
        return GetSingleRunParamsRequest.deserialize(bytes);
    }
}
export class GetSingleRunParamsResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        err?: ErrMsg;
        src_chain_id?: number;
        proof_data?: ProofData;
        merkle_root?: string;
        merkle_proof?: string[];
        node_index?: number;
        app_circuit_output?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [5], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("err" in data && data.err != undefined) {
                this.err = data.err;
            }
            if ("src_chain_id" in data && data.src_chain_id != undefined) {
                this.src_chain_id = data.src_chain_id;
            }
            if ("proof_data" in data && data.proof_data != undefined) {
                this.proof_data = data.proof_data;
            }
            if ("merkle_root" in data && data.merkle_root != undefined) {
                this.merkle_root = data.merkle_root;
            }
            if ("merkle_proof" in data && data.merkle_proof != undefined) {
                this.merkle_proof = data.merkle_proof;
            }
            if ("node_index" in data && data.node_index != undefined) {
                this.node_index = data.node_index;
            }
            if ("app_circuit_output" in data && data.app_circuit_output != undefined) {
                this.app_circuit_output = data.app_circuit_output;
            }
        }
    }
    get err() {
        return pb_1.Message.getWrapperField(this, ErrMsg, 1) as ErrMsg;
    }
    set err(value: ErrMsg) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get has_err() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get src_chain_id() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set src_chain_id(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    get proof_data() {
        return pb_1.Message.getWrapperField(this, ProofData, 3) as ProofData;
    }
    set proof_data(value: ProofData) {
        pb_1.Message.setWrapperField(this, 3, value);
    }
    get has_proof_data() {
        return pb_1.Message.getField(this, 3) != null;
    }
    get merkle_root() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set merkle_root(value: string) {
        pb_1.Message.setField(this, 4, value);
    }
    get merkle_proof() {
        return pb_1.Message.getFieldWithDefault(this, 5, []) as string[];
    }
    set merkle_proof(value: string[]) {
        pb_1.Message.setField(this, 5, value);
    }
    get node_index() {
        return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
    }
    set node_index(value: number) {
        pb_1.Message.setField(this, 6, value);
    }
    get app_circuit_output() {
        return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
    }
    set app_circuit_output(value: string) {
        pb_1.Message.setField(this, 7, value);
    }
    static fromObject(data: {
        err?: ReturnType<typeof ErrMsg.prototype.toObject>;
        src_chain_id?: number;
        proof_data?: ReturnType<typeof ProofData.prototype.toObject>;
        merkle_root?: string;
        merkle_proof?: string[];
        node_index?: number;
        app_circuit_output?: string;
    }): GetSingleRunParamsResponse {
        const message = new GetSingleRunParamsResponse({});
        if (data.err != null) {
            message.err = ErrMsg.fromObject(data.err);
        }
        if (data.src_chain_id != null) {
            message.src_chain_id = data.src_chain_id;
        }
        if (data.proof_data != null) {
            message.proof_data = ProofData.fromObject(data.proof_data);
        }
        if (data.merkle_root != null) {
            message.merkle_root = data.merkle_root;
        }
        if (data.merkle_proof != null) {
            message.merkle_proof = data.merkle_proof;
        }
        if (data.node_index != null) {
            message.node_index = data.node_index;
        }
        if (data.app_circuit_output != null) {
            message.app_circuit_output = data.app_circuit_output;
        }
        return message;
    }
    toObject() {
        const data: {
            err?: ReturnType<typeof ErrMsg.prototype.toObject>;
            src_chain_id?: number;
            proof_data?: ReturnType<typeof ProofData.prototype.toObject>;
            merkle_root?: string;
            merkle_proof?: string[];
            node_index?: number;
            app_circuit_output?: string;
        } = {};
        if (this.err != null) {
            data.err = this.err.toObject();
        }
        if (this.src_chain_id != null) {
            data.src_chain_id = this.src_chain_id;
        }
        if (this.proof_data != null) {
            data.proof_data = this.proof_data.toObject();
        }
        if (this.merkle_root != null) {
            data.merkle_root = this.merkle_root;
        }
        if (this.merkle_proof != null) {
            data.merkle_proof = this.merkle_proof;
        }
        if (this.node_index != null) {
            data.node_index = this.node_index;
        }
        if (this.app_circuit_output != null) {
            data.app_circuit_output = this.app_circuit_output;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_err)
            writer.writeMessage(1, this.err, () => this.err.serialize(writer));
        if (this.src_chain_id != 0)
            writer.writeUint64(2, this.src_chain_id);
        if (this.has_proof_data)
            writer.writeMessage(3, this.proof_data, () => this.proof_data.serialize(writer));
        if (this.merkle_root.length)
            writer.writeString(4, this.merkle_root);
        if (this.merkle_proof.length)
            writer.writeRepeatedString(5, this.merkle_proof);
        if (this.node_index != 0)
            writer.writeUint64(6, this.node_index);
        if (this.app_circuit_output.length)
            writer.writeString(7, this.app_circuit_output);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetSingleRunParamsResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetSingleRunParamsResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.err, () => message.err = ErrMsg.deserialize(reader));
                    break;
                case 2:
                    message.src_chain_id = reader.readUint64();
                    break;
                case 3:
                    reader.readMessage(message.proof_data, () => message.proof_data = ProofData.deserialize(reader));
                    break;
                case 4:
                    message.merkle_root = reader.readString();
                    break;
                case 5:
                    pb_1.Message.addToRepeatedField(message, 5, reader.readString());
                    break;
                case 6:
                    message.node_index = reader.readUint64();
                    break;
                case 7:
                    message.app_circuit_output = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GetSingleRunParamsResponse {
        return GetSingleRunParamsResponse.deserialize(bytes);
    }
}
export class ProofData extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        commit_hash?: string;
        /** @deprecated*/
        vk_hash?: string;
        app_commit_hash?: string;
        app_vk_hash?: string;
        smt_root?: string;
        dummy_input_commitment?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("commit_hash" in data && data.commit_hash != undefined) {
                this.commit_hash = data.commit_hash;
            }
            if ("vk_hash" in data && data.vk_hash != undefined) {
                this.vk_hash = data.vk_hash;
            }
            if ("app_commit_hash" in data && data.app_commit_hash != undefined) {
                this.app_commit_hash = data.app_commit_hash;
            }
            if ("app_vk_hash" in data && data.app_vk_hash != undefined) {
                this.app_vk_hash = data.app_vk_hash;
            }
            if ("smt_root" in data && data.smt_root != undefined) {
                this.smt_root = data.smt_root;
            }
            if ("dummy_input_commitment" in data && data.dummy_input_commitment != undefined) {
                this.dummy_input_commitment = data.dummy_input_commitment;
            }
        }
    }
    get commit_hash() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set commit_hash(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    /** @deprecated*/
    get vk_hash() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    /** @deprecated*/
    set vk_hash(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get app_commit_hash() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set app_commit_hash(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get app_vk_hash() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set app_vk_hash(value: string) {
        pb_1.Message.setField(this, 4, value);
    }
    get smt_root() {
        return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
    }
    set smt_root(value: string) {
        pb_1.Message.setField(this, 5, value);
    }
    get dummy_input_commitment() {
        return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
    }
    set dummy_input_commitment(value: string) {
        pb_1.Message.setField(this, 6, value);
    }
    static fromObject(data: {
        commit_hash?: string;
        vk_hash?: string;
        app_commit_hash?: string;
        app_vk_hash?: string;
        smt_root?: string;
        dummy_input_commitment?: string;
    }): ProofData {
        const message = new ProofData({});
        if (data.commit_hash != null) {
            message.commit_hash = data.commit_hash;
        }
        if (data.vk_hash != null) {
            message.vk_hash = data.vk_hash;
        }
        if (data.app_commit_hash != null) {
            message.app_commit_hash = data.app_commit_hash;
        }
        if (data.app_vk_hash != null) {
            message.app_vk_hash = data.app_vk_hash;
        }
        if (data.smt_root != null) {
            message.smt_root = data.smt_root;
        }
        if (data.dummy_input_commitment != null) {
            message.dummy_input_commitment = data.dummy_input_commitment;
        }
        return message;
    }
    toObject() {
        const data: {
            commit_hash?: string;
            vk_hash?: string;
            app_commit_hash?: string;
            app_vk_hash?: string;
            smt_root?: string;
            dummy_input_commitment?: string;
        } = {};
        if (this.commit_hash != null) {
            data.commit_hash = this.commit_hash;
        }
        if (this.vk_hash != null) {
            data.vk_hash = this.vk_hash;
        }
        if (this.app_commit_hash != null) {
            data.app_commit_hash = this.app_commit_hash;
        }
        if (this.app_vk_hash != null) {
            data.app_vk_hash = this.app_vk_hash;
        }
        if (this.smt_root != null) {
            data.smt_root = this.smt_root;
        }
        if (this.dummy_input_commitment != null) {
            data.dummy_input_commitment = this.dummy_input_commitment;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.commit_hash.length)
            writer.writeString(1, this.commit_hash);
        if (this.vk_hash.length)
            writer.writeString(2, this.vk_hash);
        if (this.app_commit_hash.length)
            writer.writeString(3, this.app_commit_hash);
        if (this.app_vk_hash.length)
            writer.writeString(4, this.app_vk_hash);
        if (this.smt_root.length)
            writer.writeString(5, this.smt_root);
        if (this.dummy_input_commitment.length)
            writer.writeString(6, this.dummy_input_commitment);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ProofData {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ProofData();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.commit_hash = reader.readString();
                    break;
                case 2:
                    message.vk_hash = reader.readString();
                    break;
                case 3:
                    message.app_commit_hash = reader.readString();
                    break;
                case 4:
                    message.app_vk_hash = reader.readString();
                    break;
                case 5:
                    message.smt_root = reader.readString();
                    break;
                case 6:
                    message.dummy_input_commitment = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ProofData {
        return ProofData.deserialize(bytes);
    }
}
export class SendBatchQueriesRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        chain_id?: number;
        queries?: Query[];
        target_chain_id?: number;
        option?: QueryOption;
        api_key?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("chain_id" in data && data.chain_id != undefined) {
                this.chain_id = data.chain_id;
            }
            if ("queries" in data && data.queries != undefined) {
                this.queries = data.queries;
            }
            if ("target_chain_id" in data && data.target_chain_id != undefined) {
                this.target_chain_id = data.target_chain_id;
            }
            if ("option" in data && data.option != undefined) {
                this.option = data.option;
            }
            if ("api_key" in data && data.api_key != undefined) {
                this.api_key = data.api_key;
            }
        }
    }
    get chain_id() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set chain_id(value: number) {
        pb_1.Message.setField(this, 1, value);
    }
    get queries() {
        return pb_1.Message.getRepeatedWrapperField(this, Query, 2) as Query[];
    }
    set queries(value: Query[]) {
        pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    get target_chain_id() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set target_chain_id(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    get option() {
        return pb_1.Message.getFieldWithDefault(this, 4, QueryOption.ZK_MODE) as QueryOption;
    }
    set option(value: QueryOption) {
        pb_1.Message.setField(this, 4, value);
    }
    get api_key() {
        return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
    }
    set api_key(value: string) {
        pb_1.Message.setField(this, 5, value);
    }
    static fromObject(data: {
        chain_id?: number;
        queries?: ReturnType<typeof Query.prototype.toObject>[];
        target_chain_id?: number;
        option?: QueryOption;
        api_key?: string;
    }): SendBatchQueriesRequest {
        const message = new SendBatchQueriesRequest({});
        if (data.chain_id != null) {
            message.chain_id = data.chain_id;
        }
        if (data.queries != null) {
            message.queries = data.queries.map(item => Query.fromObject(item));
        }
        if (data.target_chain_id != null) {
            message.target_chain_id = data.target_chain_id;
        }
        if (data.option != null) {
            message.option = data.option;
        }
        if (data.api_key != null) {
            message.api_key = data.api_key;
        }
        return message;
    }
    toObject() {
        const data: {
            chain_id?: number;
            queries?: ReturnType<typeof Query.prototype.toObject>[];
            target_chain_id?: number;
            option?: QueryOption;
            api_key?: string;
        } = {};
        if (this.chain_id != null) {
            data.chain_id = this.chain_id;
        }
        if (this.queries != null) {
            data.queries = this.queries.map((item: Query) => item.toObject());
        }
        if (this.target_chain_id != null) {
            data.target_chain_id = this.target_chain_id;
        }
        if (this.option != null) {
            data.option = this.option;
        }
        if (this.api_key != null) {
            data.api_key = this.api_key;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.chain_id != 0)
            writer.writeUint64(1, this.chain_id);
        if (this.queries.length)
            writer.writeRepeatedMessage(2, this.queries, (item: Query) => item.serialize(writer));
        if (this.target_chain_id != 0)
            writer.writeUint64(3, this.target_chain_id);
        if (this.option != QueryOption.ZK_MODE)
            writer.writeEnum(4, this.option);
        if (this.api_key.length)
            writer.writeString(5, this.api_key);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SendBatchQueriesRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SendBatchQueriesRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.chain_id = reader.readUint64();
                    break;
                case 2:
                    reader.readMessage(message.queries, () => pb_1.Message.addToRepeatedWrapperField(message, 2, Query.deserialize(reader), Query));
                    break;
                case 3:
                    message.target_chain_id = reader.readUint64();
                    break;
                case 4:
                    message.option = reader.readEnum();
                    break;
                case 5:
                    message.api_key = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SendBatchQueriesRequest {
        return SendBatchQueriesRequest.deserialize(bytes);
    }
}
export class Query extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        receipt_infos?: dependency_1.ReceiptInfo[];
        storage_query_infos?: dependency_1.StorageQueryInfo[];
        transaction_infos?: dependency_1.TransactionInfo[];
        app_circuit_info?: dependency_2.AppCircuitInfoWithProof;
        /** @deprecated*/
        use_plonky2?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1, 2, 3], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("receipt_infos" in data && data.receipt_infos != undefined) {
                this.receipt_infos = data.receipt_infos;
            }
            if ("storage_query_infos" in data && data.storage_query_infos != undefined) {
                this.storage_query_infos = data.storage_query_infos;
            }
            if ("transaction_infos" in data && data.transaction_infos != undefined) {
                this.transaction_infos = data.transaction_infos;
            }
            if ("app_circuit_info" in data && data.app_circuit_info != undefined) {
                this.app_circuit_info = data.app_circuit_info;
            }
            if ("use_plonky2" in data && data.use_plonky2 != undefined) {
                this.use_plonky2 = data.use_plonky2;
            }
        }
    }
    get receipt_infos() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.ReceiptInfo, 1) as dependency_1.ReceiptInfo[];
    }
    set receipt_infos(value: dependency_1.ReceiptInfo[]) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    get storage_query_infos() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.StorageQueryInfo, 2) as dependency_1.StorageQueryInfo[];
    }
    set storage_query_infos(value: dependency_1.StorageQueryInfo[]) {
        pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    get transaction_infos() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.TransactionInfo, 3) as dependency_1.TransactionInfo[];
    }
    set transaction_infos(value: dependency_1.TransactionInfo[]) {
        pb_1.Message.setRepeatedWrapperField(this, 3, value);
    }
    get app_circuit_info() {
        return pb_1.Message.getWrapperField(this, dependency_2.AppCircuitInfoWithProof, 4) as dependency_2.AppCircuitInfoWithProof;
    }
    set app_circuit_info(value: dependency_2.AppCircuitInfoWithProof) {
        pb_1.Message.setWrapperField(this, 4, value);
    }
    get has_app_circuit_info() {
        return pb_1.Message.getField(this, 4) != null;
    }
    /** @deprecated*/
    get use_plonky2() {
        return pb_1.Message.getFieldWithDefault(this, 5, false) as boolean;
    }
    /** @deprecated*/
    set use_plonky2(value: boolean) {
        pb_1.Message.setField(this, 5, value);
    }
    static fromObject(data: {
        receipt_infos?: ReturnType<typeof dependency_1.ReceiptInfo.prototype.toObject>[];
        storage_query_infos?: ReturnType<typeof dependency_1.StorageQueryInfo.prototype.toObject>[];
        transaction_infos?: ReturnType<typeof dependency_1.TransactionInfo.prototype.toObject>[];
        app_circuit_info?: ReturnType<typeof dependency_2.AppCircuitInfoWithProof.prototype.toObject>;
        use_plonky2?: boolean;
    }): Query {
        const message = new Query({});
        if (data.receipt_infos != null) {
            message.receipt_infos = data.receipt_infos.map(item => dependency_1.ReceiptInfo.fromObject(item));
        }
        if (data.storage_query_infos != null) {
            message.storage_query_infos = data.storage_query_infos.map(item => dependency_1.StorageQueryInfo.fromObject(item));
        }
        if (data.transaction_infos != null) {
            message.transaction_infos = data.transaction_infos.map(item => dependency_1.TransactionInfo.fromObject(item));
        }
        if (data.app_circuit_info != null) {
            message.app_circuit_info = dependency_2.AppCircuitInfoWithProof.fromObject(data.app_circuit_info);
        }
        if (data.use_plonky2 != null) {
            message.use_plonky2 = data.use_plonky2;
        }
        return message;
    }
    toObject() {
        const data: {
            receipt_infos?: ReturnType<typeof dependency_1.ReceiptInfo.prototype.toObject>[];
            storage_query_infos?: ReturnType<typeof dependency_1.StorageQueryInfo.prototype.toObject>[];
            transaction_infos?: ReturnType<typeof dependency_1.TransactionInfo.prototype.toObject>[];
            app_circuit_info?: ReturnType<typeof dependency_2.AppCircuitInfoWithProof.prototype.toObject>;
            use_plonky2?: boolean;
        } = {};
        if (this.receipt_infos != null) {
            data.receipt_infos = this.receipt_infos.map((item: dependency_1.ReceiptInfo) => item.toObject());
        }
        if (this.storage_query_infos != null) {
            data.storage_query_infos = this.storage_query_infos.map((item: dependency_1.StorageQueryInfo) => item.toObject());
        }
        if (this.transaction_infos != null) {
            data.transaction_infos = this.transaction_infos.map((item: dependency_1.TransactionInfo) => item.toObject());
        }
        if (this.app_circuit_info != null) {
            data.app_circuit_info = this.app_circuit_info.toObject();
        }
        if (this.use_plonky2 != null) {
            data.use_plonky2 = this.use_plonky2;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.receipt_infos.length)
            writer.writeRepeatedMessage(1, this.receipt_infos, (item: dependency_1.ReceiptInfo) => item.serialize(writer));
        if (this.storage_query_infos.length)
            writer.writeRepeatedMessage(2, this.storage_query_infos, (item: dependency_1.StorageQueryInfo) => item.serialize(writer));
        if (this.transaction_infos.length)
            writer.writeRepeatedMessage(3, this.transaction_infos, (item: dependency_1.TransactionInfo) => item.serialize(writer));
        if (this.has_app_circuit_info)
            writer.writeMessage(4, this.app_circuit_info, () => this.app_circuit_info.serialize(writer));
        if (this.use_plonky2 != false)
            writer.writeBool(5, this.use_plonky2);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Query {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Query();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.receipt_infos, () => pb_1.Message.addToRepeatedWrapperField(message, 1, dependency_1.ReceiptInfo.deserialize(reader), dependency_1.ReceiptInfo));
                    break;
                case 2:
                    reader.readMessage(message.storage_query_infos, () => pb_1.Message.addToRepeatedWrapperField(message, 2, dependency_1.StorageQueryInfo.deserialize(reader), dependency_1.StorageQueryInfo));
                    break;
                case 3:
                    reader.readMessage(message.transaction_infos, () => pb_1.Message.addToRepeatedWrapperField(message, 3, dependency_1.TransactionInfo.deserialize(reader), dependency_1.TransactionInfo));
                    break;
                case 4:
                    reader.readMessage(message.app_circuit_info, () => message.app_circuit_info = dependency_2.AppCircuitInfoWithProof.deserialize(reader));
                    break;
                case 5:
                    message.use_plonky2 = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Query {
        return Query.deserialize(bytes);
    }
}
export class SendBatchQueriesResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        err?: ErrMsg;
        query_keys?: QueryKey[];
        fee?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("err" in data && data.err != undefined) {
                this.err = data.err;
            }
            if ("query_keys" in data && data.query_keys != undefined) {
                this.query_keys = data.query_keys;
            }
            if ("fee" in data && data.fee != undefined) {
                this.fee = data.fee;
            }
        }
    }
    get err() {
        return pb_1.Message.getWrapperField(this, ErrMsg, 1) as ErrMsg;
    }
    set err(value: ErrMsg) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get has_err() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get query_keys() {
        return pb_1.Message.getRepeatedWrapperField(this, QueryKey, 2) as QueryKey[];
    }
    set query_keys(value: QueryKey[]) {
        pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    get fee() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set fee(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    static fromObject(data: {
        err?: ReturnType<typeof ErrMsg.prototype.toObject>;
        query_keys?: ReturnType<typeof QueryKey.prototype.toObject>[];
        fee?: string;
    }): SendBatchQueriesResponse {
        const message = new SendBatchQueriesResponse({});
        if (data.err != null) {
            message.err = ErrMsg.fromObject(data.err);
        }
        if (data.query_keys != null) {
            message.query_keys = data.query_keys.map(item => QueryKey.fromObject(item));
        }
        if (data.fee != null) {
            message.fee = data.fee;
        }
        return message;
    }
    toObject() {
        const data: {
            err?: ReturnType<typeof ErrMsg.prototype.toObject>;
            query_keys?: ReturnType<typeof QueryKey.prototype.toObject>[];
            fee?: string;
        } = {};
        if (this.err != null) {
            data.err = this.err.toObject();
        }
        if (this.query_keys != null) {
            data.query_keys = this.query_keys.map((item: QueryKey) => item.toObject());
        }
        if (this.fee != null) {
            data.fee = this.fee;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_err)
            writer.writeMessage(1, this.err, () => this.err.serialize(writer));
        if (this.query_keys.length)
            writer.writeRepeatedMessage(2, this.query_keys, (item: QueryKey) => item.serialize(writer));
        if (this.fee.length)
            writer.writeString(3, this.fee);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SendBatchQueriesResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SendBatchQueriesResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.err, () => message.err = ErrMsg.deserialize(reader));
                    break;
                case 2:
                    reader.readMessage(message.query_keys, () => pb_1.Message.addToRepeatedWrapperField(message, 2, QueryKey.deserialize(reader), QueryKey));
                    break;
                case 3:
                    message.fee = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SendBatchQueriesResponse {
        return SendBatchQueriesResponse.deserialize(bytes);
    }
}
export class QueryKey extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        query_hash?: string;
        nonce?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("query_hash" in data && data.query_hash != undefined) {
                this.query_hash = data.query_hash;
            }
            if ("nonce" in data && data.nonce != undefined) {
                this.nonce = data.nonce;
            }
        }
    }
    get query_hash() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set query_hash(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get nonce() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set nonce(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        query_hash?: string;
        nonce?: number;
    }): QueryKey {
        const message = new QueryKey({});
        if (data.query_hash != null) {
            message.query_hash = data.query_hash;
        }
        if (data.nonce != null) {
            message.nonce = data.nonce;
        }
        return message;
    }
    toObject() {
        const data: {
            query_hash?: string;
            nonce?: number;
        } = {};
        if (this.query_hash != null) {
            data.query_hash = this.query_hash;
        }
        if (this.nonce != null) {
            data.nonce = this.nonce;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.query_hash.length)
            writer.writeString(1, this.query_hash);
        if (this.nonce != 0)
            writer.writeUint64(2, this.nonce);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QueryKey {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QueryKey();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.query_hash = reader.readString();
                    break;
                case 2:
                    message.nonce = reader.readUint64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): QueryKey {
        return QueryKey.deserialize(bytes);
    }
}
interface GrpcUnaryServiceInterface<P, R> {
    (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
}
interface GrpcStreamServiceInterface<P, R> {
    (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
}
interface GrpWritableServiceInterface<P, R> {
    (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
}
interface GrpcChunkServiceInterface<P, R> {
    (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
}
interface GrpcPromiseServiceInterface<P, R> {
    (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
    (message: P, options?: grpc_1.CallOptions): Promise<R>;
}
export abstract class UnimplementedGatewayService {
    static definition = {
        PrepareQuery: {
            path: "/brevis.Gateway/PrepareQuery",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message: PrepareQueryRequest) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes: Buffer) => PrepareQueryRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message: PrepareQueryResponse) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes: Buffer) => PrepareQueryResponse.deserialize(new Uint8Array(bytes))
        },
        SubmitAppCircuitProof: {
            path: "/brevis.Gateway/SubmitAppCircuitProof",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message: SubmitAppCircuitProofRequest) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes: Buffer) => SubmitAppCircuitProofRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message: SubmitAppCircuitProofResponse) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes: Buffer) => SubmitAppCircuitProofResponse.deserialize(new Uint8Array(bytes))
        },
        GetQueryStatus: {
            path: "/brevis.Gateway/GetQueryStatus",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message: GetQueryStatusRequest) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes: Buffer) => GetQueryStatusRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message: GetQueryStatusResponse) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes: Buffer) => GetQueryStatusResponse.deserialize(new Uint8Array(bytes))
        },
        GetQueryInfoForOP: {
            path: "/brevis.Gateway/GetQueryInfoForOP",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message: GetQueryInfoForOPRequest) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes: Buffer) => GetQueryInfoForOPRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message: GetQueryInfoForOPResponse) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes: Buffer) => GetQueryInfoForOPResponse.deserialize(new Uint8Array(bytes))
        },
        GetSingleRunParams: {
            path: "/brevis.Gateway/GetSingleRunParams",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message: GetSingleRunParamsRequest) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes: Buffer) => GetSingleRunParamsRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message: GetSingleRunParamsResponse) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes: Buffer) => GetSingleRunParamsResponse.deserialize(new Uint8Array(bytes))
        },
        SendBatchQueries: {
            path: "/brevis.Gateway/SendBatchQueries",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message: SendBatchQueriesRequest) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes: Buffer) => SendBatchQueriesRequest.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message: SendBatchQueriesResponse) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes: Buffer) => SendBatchQueriesResponse.deserialize(new Uint8Array(bytes))
        }
    };
    [method: string]: grpc_1.UntypedHandleCall;
    abstract PrepareQuery(call: grpc_1.ServerUnaryCall<PrepareQueryRequest, PrepareQueryResponse>, callback: grpc_1.sendUnaryData<PrepareQueryResponse>): void;
    abstract SubmitAppCircuitProof(call: grpc_1.ServerUnaryCall<SubmitAppCircuitProofRequest, SubmitAppCircuitProofResponse>, callback: grpc_1.sendUnaryData<SubmitAppCircuitProofResponse>): void;
    abstract GetQueryStatus(call: grpc_1.ServerUnaryCall<GetQueryStatusRequest, GetQueryStatusResponse>, callback: grpc_1.sendUnaryData<GetQueryStatusResponse>): void;
    abstract GetQueryInfoForOP(call: grpc_1.ServerUnaryCall<GetQueryInfoForOPRequest, GetQueryInfoForOPResponse>, callback: grpc_1.sendUnaryData<GetQueryInfoForOPResponse>): void;
    abstract GetSingleRunParams(call: grpc_1.ServerUnaryCall<GetSingleRunParamsRequest, GetSingleRunParamsResponse>, callback: grpc_1.sendUnaryData<GetSingleRunParamsResponse>): void;
    abstract SendBatchQueries(call: grpc_1.ServerUnaryCall<SendBatchQueriesRequest, SendBatchQueriesResponse>, callback: grpc_1.sendUnaryData<SendBatchQueriesResponse>): void;
}
export class GatewayClient extends grpc_1.makeGenericClientConstructor(UnimplementedGatewayService.definition, "Gateway", {}) {
    constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
        super(address, credentials, options);
    }
    PrepareQuery: GrpcPromiseServiceInterface<PrepareQueryRequest, PrepareQueryResponse> = (message: PrepareQueryRequest, metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): Promise<PrepareQueryResponse> => { if (!metadata) {
        metadata = new grpc_1.Metadata;
    } if (!options) {
        options = {};
    } return new Promise((resolve, reject) => super.PrepareQuery(message, metadata, options, (error: grpc_1.ServiceError, response: PrepareQueryResponse) => {
        if (error) {
            reject(error);
        }
        else {
            resolve(response);
        }
    })); };
    SubmitAppCircuitProof: GrpcPromiseServiceInterface<SubmitAppCircuitProofRequest, SubmitAppCircuitProofResponse> = (message: SubmitAppCircuitProofRequest, metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): Promise<SubmitAppCircuitProofResponse> => { if (!metadata) {
        metadata = new grpc_1.Metadata;
    } if (!options) {
        options = {};
    } return new Promise((resolve, reject) => super.SubmitAppCircuitProof(message, metadata, options, (error: grpc_1.ServiceError, response: SubmitAppCircuitProofResponse) => {
        if (error) {
            reject(error);
        }
        else {
            resolve(response);
        }
    })); };
    GetQueryStatus: GrpcPromiseServiceInterface<GetQueryStatusRequest, GetQueryStatusResponse> = (message: GetQueryStatusRequest, metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): Promise<GetQueryStatusResponse> => { if (!metadata) {
        metadata = new grpc_1.Metadata;
    } if (!options) {
        options = {};
    } return new Promise((resolve, reject) => super.GetQueryStatus(message, metadata, options, (error: grpc_1.ServiceError, response: GetQueryStatusResponse) => {
        if (error) {
            reject(error);
        }
        else {
            resolve(response);
        }
    })); };
    GetQueryInfoForOP: GrpcPromiseServiceInterface<GetQueryInfoForOPRequest, GetQueryInfoForOPResponse> = (message: GetQueryInfoForOPRequest, metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): Promise<GetQueryInfoForOPResponse> => { if (!metadata) {
        metadata = new grpc_1.Metadata;
    } if (!options) {
        options = {};
    } return new Promise((resolve, reject) => super.GetQueryInfoForOP(message, metadata, options, (error: grpc_1.ServiceError, response: GetQueryInfoForOPResponse) => {
        if (error) {
            reject(error);
        }
        else {
            resolve(response);
        }
    })); };
    GetSingleRunParams: GrpcPromiseServiceInterface<GetSingleRunParamsRequest, GetSingleRunParamsResponse> = (message: GetSingleRunParamsRequest, metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): Promise<GetSingleRunParamsResponse> => { if (!metadata) {
        metadata = new grpc_1.Metadata;
    } if (!options) {
        options = {};
    } return new Promise((resolve, reject) => super.GetSingleRunParams(message, metadata, options, (error: grpc_1.ServiceError, response: GetSingleRunParamsResponse) => {
        if (error) {
            reject(error);
        }
        else {
            resolve(response);
        }
    })); };
    SendBatchQueries: GrpcPromiseServiceInterface<SendBatchQueriesRequest, SendBatchQueriesResponse> = (message: SendBatchQueriesRequest, metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): Promise<SendBatchQueriesResponse> => { if (!metadata) {
        metadata = new grpc_1.Metadata;
    } if (!options) {
        options = {};
    } return new Promise((resolve, reject) => super.SendBatchQueries(message, metadata, options, (error: grpc_1.ServiceError, response: SendBatchQueriesResponse) => {
        if (error) {
            reject(error);
        }
        else {
            resolve(response);
        }
    })); };
}
